### ISSUE TITLE
Guid != ObjectId

### ISSUE THREAD

**Issue by justinmchase** [buvinghausen/SequentialGuid#11]
You said you implemented the spec but then said its a 16 byte guid but the in the objectid spec it says

> Returns a new [ObjectId](https://www.mongodb.com/docs/manual/reference/bson-types/#std-label-objectid). The 12-byte [ObjectId](https://www.mongodb.com/docs/manual/reference/bson-types/#std-label-objectid)

Seems like this should have an actual ObjectId type also, which is 12 bytes.

**Comment by buvinghausen** [comment]
I believe you misinterpreted the point of this library.... It is to be able to use the Guid struct which is ubiquitous across all languages and is completely agnostic of Mongo it just generates sequential Guids using the same sorting algorithm that Mongo wrote for their ObjectId specification.

If you want to tie your API code to your underlying persistence layer be my guest and use their driver.  If you want to be able to generate sorted guids in webassembly and use a format that is universally accepted and understood then this is the library for you.
